version: "3.9"  
services:
  db:
    image: mysql:latest
    container_name: mysql
    ports:
        - 3307:3306
    volumes:
        - /home/rod/mysql_data:/var/lib/mysql
        - /home/rod/mysql_dump:/mysql_dump
        - /home/rod/mysql_conf/conf.d:/etc/mysql/conf.d
    environment:
        MYSQL_ROOT_PASSWORD: 123
        MYSQL_DATABASE: test_db
    restart: always
