---
elasticsearch:
  hosts:
    elasticsearch:
        ansible_host: 192.168.122.33
        ansible_connection: ssh
        ansible_user: root
kibana:
  hosts:
    kibana:
        ansible_host: 192.168.122.10
        ansible_connection: ssh
        ansible_user: root

app:
  hosts:
    app:
        ansible_host: 192.168.122.188
        ansible_connection: ssh
        ansible_user: root
